/**
 * Sandbox tools — expose code execution as agent tools.
 *
 * Gracefully returns an empty object when E2B is not configured,
 * so the agent runs normally without sandbox capabilities.
 */

import { tool } from 'ai';
import { z } from 'zod';
import { getOrCreateSession } from './manager';

export function createSandboxTools(orgId: string, threadId: string) {
  // If E2B is not configured, return no tools — the agent works fine without them
  if (!process.env.E2B_API_KEY) return {};

  const getSession = () => getOrCreateSession(orgId, threadId);

  return {
    execute_code: tool({
      description:
        'Write and run code in a sandboxed environment. Use this for calculations, data processing, ' +
        'file generation, analysis, charts, or any task that benefits from real computation. ' +
        'Python (with pandas, numpy, matplotlib pre-installed), JavaScript, and bash are available. ' +
        'Write complete, runnable scripts. Print results to stdout.',
      inputSchema: z.object({
        language: z.enum(['python', 'javascript', 'bash']).describe('Language to execute'),
        code: z.string().describe('Complete, runnable code to execute'),
        description: z.string().describe('Brief description of what this code does'),
      }),
      execute: async ({ language, code }) => {
        try {
          const session = getSession();
          const result = await session.execute(code, language);
          if (result.exitCode !== 0) {
            return {
              success: false,
              exitCode: result.exitCode,
              stdout: result.stdout || undefined,
              stderr: result.stderr || undefined,
              error: result.error || result.stderr,
            };
          }
          return {
            success: true,
            exitCode: 0,
            output: result.stdout,
            stderr: result.stderr || undefined,
          };
        } catch (error) {
          return { success: false, error: String(error) };
        }
      },
    }),

    install_packages: tool({
      description:
        'Install packages in the sandbox before running code that needs them. ' +
        'Installs via pip (Python packages). Call this before execute_code if you need libraries ' +
        'beyond the pre-installed ones (pandas, numpy, matplotlib).',
      inputSchema: z.object({
        packages: z.array(z.string()).describe('Package names to install, e.g. ["scikit-learn", "requests"]'),
      }),
      execute: async ({ packages }) => {
        try {
          const session = getSession();
          const result = await session.installPackages(packages);
          if (result.exitCode !== 0) {
            return { installed: false, error: result.stderr };
          }
          return { installed: true, packages };
        } catch (error) {
          return { installed: false, error: String(error) };
        }
      },
    }),

    write_file: tool({
      description:
        'Write a file to the sandbox filesystem. Use this to create data files, configs, or scripts ' +
        'that you will process with execute_code. Files persist for the duration of the conversation.',
      inputSchema: z.object({
        path: z.string().describe('Absolute path in the sandbox, e.g. "/home/user/data.csv"'),
        content: z.string().describe('File content to write'),
      }),
      execute: async ({ path, content }) => {
        try {
          const session = getSession();
          await session.writeFile(path, content);
          return { written: true, path, bytes: content.length };
        } catch (error) {
          return { written: false, error: String(error) };
        }
      },
    }),

    read_file: tool({
      description:
        'Read a file from the sandbox filesystem. Use this to retrieve output files generated by ' +
        'execute_code — results, CSVs, logs, etc.',
      inputSchema: z.object({
        path: z.string().describe('Absolute path in the sandbox to read'),
      }),
      execute: async ({ path }) => {
        try {
          const session = getSession();
          const content = await session.readFile(path);
          return { success: true, path, content };
        } catch (error) {
          return { success: false, error: String(error) };
        }
      },
    }),
  };
}
